### ISSUE TITLE
Ability to define a new delimiter? 

### ISSUE THREAD

**Issue by fullmetal-fred** [beasteers/randomname#6]
Would be suuuper nice to be able to change between other delimiters...like _ , ; : etc. 
So an option flag...
`randomname generate adj/ noun/ --delim=_`
If you're busy I can probably work up a PR for it :)

**Comment by beasteers** [comment]
Well it's your lucky day :) you can already do it like:

`randomname generate adj/ nouns/ --sep=_`

(same thing applies to the python interface `randomname.generate('a/', 'n/', sep='_')`)

That's my bad for not putting together proper docs lol

**Comment by fullmetal-fred** [comment]
Niiiiice! Confirmed and thanks!
